FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y apt-utils curl
RUN apt-get install -y gcc g++ libboost-all-dev cmake
RUN apt-get install -y doxygen libgraphicsmagick-q16-3 libssl-dev libpq-dev libfcgi-dev
RUN apt-get install -y witty witty-dev
RUN mkdir /dproj
RUN ldconfig
