FROM alpine
RUN apk update
RUN apk add bash wget
RUN apk add vim
RUN apk add gcc g++ boost cmake
RUN apk add openssl libpq fcgi
RUN apk add wt-dev
#RUN rm -rf /var/cache/apk/*


#FROM ubuntu
#RUN apt-get update
#RUN apt-get install -y apt-utils curl
#RUN apt-get install -y gcc g++ libboost-all-dev cmake
#RUN apt-get install -y doxygen libgraphicsmagick-q16-3 libpq-dev libssl-dev libfcgi-dev
#RUN apt-get install -y witty witty-dev
#RUN mkdir /dproj
#RUN ldconfig
